-- MySQL Script generated by MySQL Workbench
-- Mon May 23 22:50:13 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EdgoDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EdgoDB` ;

-- -----------------------------------------------------
-- Schema EdgoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EdgoDB` DEFAULT CHARACTER SET utf8 ;
USE `EdgoDB` ;

-- -----------------------------------------------------
-- Table `EdgoDB`.`Gene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`Gene` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`Gene` (
  `ENTREZ_GENE_ID` INT UNSIGNED NOT NULL,
  `HUGO_GENE_SYMBOL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ENTREZ_GENE_ID`),
  UNIQUE INDEX `CCSB_ORF_ID_UNIQUE` (`HUGO_GENE_SYMBOL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`OpenReadingFrame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`OpenReadingFrame` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`OpenReadingFrame` (
  `CCSB_ORF_ID` INT NOT NULL,
  `ORF_LENGTH` INT NOT NULL,
  `REF_ORF_SEQ` VARCHAR(5000) NOT NULL,
  `ENTREZ_GENE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CCSB_ORF_ID`),
  INDEX `fk_OpenReadingFrame_Gene1_idx` (`ENTREZ_GENE_ID` ASC),
  CONSTRAINT `fk_OpenReadingFrame_Gene1`
    FOREIGN KEY (`ENTREZ_GENE_ID`)
    REFERENCES `EdgoDB`.`Gene` (`ENTREZ_GENE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`Transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`Transcript` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`Transcript` (
  `REFSEQ_ID` VARCHAR(45) NOT NULL,
  `ENTREZ_GENE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`REFSEQ_ID`),
  INDEX `fk_Transcript_Gene1_idx` (`ENTREZ_GENE_ID` ASC),
  CONSTRAINT `fk_Transcript_Gene1`
    FOREIGN KEY (`ENTREZ_GENE_ID`)
    REFERENCES `EdgoDB`.`Gene` (`ENTREZ_GENE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`Variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`Variant` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`Variant` (
  `VARIANT_ID` INT NOT NULL AUTO_INCREMENT,
  `DBSNP_ID` VARCHAR(45) NULL,
  `CCSB_MUTATION_ID` INT NOT NULL,
  `PMID` INT NOT NULL,
  `HGVS_CDNA_ID` VARCHAR(45) NOT NULL,
  `HGVS_PROTEIN_ID` VARCHAR(45) NOT NULL,
  `HGMD_ACC_NUM` VARCHAR(20) NOT NULL,
  `MUT_DISEASE_CAUSING` VARCHAR(5) NOT NULL,
  `ORFEOME_NT_POS` INT(10) NOT NULL,
  `REF_NT` CHAR(1) NOT NULL,
  `ALT_NT` CHAR(1) NOT NULL,
  `HGMD_CODON_POS` INT(10) NOT NULL COMMENT 'together with EXP_CODON and MUT_CODON forms AA_changed_HGMD ',
  `REF_CODON` CHAR(3) NOT NULL,
  `ALT_CODON` CHAR(3) NOT NULL,
  `REF_AA` CHAR(1) NOT NULL,
  `ALT_AA` CHAR(1) NOT NULL,
  `CHR` INT NOT NULL,
  `CHR_COORDINATE` INT UNSIGNED NOT NULL,
  `REFSEQ_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VARIANT_ID`),
  UNIQUE INDEX `CCSB_MUTATION_ID_UNIQUE` (`CCSB_MUTATION_ID` ASC),
  UNIQUE INDEX `HGMD_ACC_NUM_UNIQUE` (`HGMD_ACC_NUM` ASC),
  UNIQUE INDEX `HGVS_PROTEIN_ID_UNIQUE` (`HGVS_PROTEIN_ID` ASC),
  UNIQUE INDEX `DBSNP_ID_UNIQUE` (`DBSNP_ID` ASC),
  UNIQUE INDEX `HGVS_CDNA_ID_UNIQUE` (`HGVS_CDNA_ID` ASC),
  UNIQUE INDEX `PMID_UNIQUE` (`PMID` ASC),
  INDEX `fk_Variant_Transcript1_idx` (`REFSEQ_ID` ASC),
  UNIQUE INDEX `REFSEQ_ID_UNIQUE` (`REFSEQ_ID` ASC),
  CONSTRAINT `fk_Variant_Transcript1`
    FOREIGN KEY (`REFSEQ_ID`)
    REFERENCES `EdgoDB`.`Transcript` (`REFSEQ_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`LocalCollection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`LocalCollection` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`LocalCollection` (
  `ENTRY_PLATE` VARCHAR(45) NOT NULL,
  `ENTRY_WELL` VARCHAR(45) NOT NULL,
  `MUT_PLATE` VARCHAR(45) NULL,
  `MUT_WELL` VARCHAR(45) NULL,
  `VARIANT_ID` INT NOT NULL,
  PRIMARY KEY (`ENTRY_PLATE`, `ENTRY_WELL`),
  INDEX `fk_LocalCollection_Variant1_idx` (`VARIANT_ID` ASC),
  UNIQUE INDEX `VARIANT_ID_UNIQUE` (`VARIANT_ID` ASC),
  UNIQUE INDEX `MUT_PLATE_UNIQUE` (`MUT_PLATE` ASC),
  UNIQUE INDEX `MUT_WELL_UNIQUE` (`MUT_WELL` ASC),
  CONSTRAINT `fk_LocalCollection_Variant1`
    FOREIGN KEY (`VARIANT_ID`)
    REFERENCES `EdgoDB`.`Variant` (`VARIANT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`Measurement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`Measurement` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`Measurement` (
  `VARIANT_ID` INT NOT NULL,
  `INTERACTOR` VARCHAR(45) NOT NULL,
  `INTERACTION_WT_Z_SCORE` INT NULL,
  `INTERACTION_MUT_Z_SCORE` INT NULL,
  `INTERACTION_DIFF` DECIMAL(20,20) NULL,
  `INTERACTION_SIGNIFICANT` TINYINT(1) NULL,
  `EXPRESSION_WT_ELISA` DECIMAL(20,20) NULL,
  `EXPRESSION_MUT_ELISA` DECIMAL(20,20) NULL,
  `EXPRESSION_RATIO` DECIMAL(20,20) NULL,
  PRIMARY KEY (`INTERACTOR`, `VARIANT_ID`),
  INDEX `fk_Measurement_Variant1_idx` (`VARIANT_ID` ASC),
  CONSTRAINT `fk_Measurement_Variant1`
    FOREIGN KEY (`VARIANT_ID`)
    REFERENCES `EdgoDB`.`Variant` (`VARIANT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`SummaryStatistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`SummaryStatistics` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`SummaryStatistics` (
  `VARIANT_ID` INT NOT NULL,
  `WT_ELISA_AVERAGE` DECIMAL(20,20) NULL,
  `MUT_ELISA_AVERAGE` DECIMAL(20,20) NULL,
  `WT_EXPRESSED` TINYINT(1) NULL,
  `MUT_EXPRESSED` TINYINT(1) NULL,
  `ELISA_RATIO_AVERAGE` DECIMAL(20,20) NULL,
  `ELISA_LOG2_RATIO` DECIMAL(20,20) NULL,
  `ELISA_LOG2_RATIO_P_VALUE` VARCHAR(20) NULL,
  PRIMARY KEY (`VARIANT_ID`),
  CONSTRAINT `fk_SummaryStatistics_Variant1`
    FOREIGN KEY (`VARIANT_ID`)
    REFERENCES `EdgoDB`.`Variant` (`VARIANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`StructuralEffect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`StructuralEffect` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`StructuralEffect` (
  `STRUCTURAL_EFFECT_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SECONDARY_STRUCTURE` VARCHAR(1) NULL,
  `SOLVENT_ACCESSIBILITY` VARCHAR(1) NULL,
  `HYDROPHOBICITY_CHANGE` DECIMAL(10,10) NULL,
  `EVO_CONSERVATION` DECIMAL(10,10) NULL,
  `PROTEIN_HAS_TMD` TINYINT(1) NULL,
  `PROTEIN_HAS_SIGNAL_PEPTIDE` TINYINT(1) NULL,
  `POLYPHEN_SCORE` DECIMAL(10,10) NULL,
  `POLYPHEN_CLASS` VARCHAR(45) NULL,
  `SUSPECT_AVERAGE` INT NULL,
  `SUSPECT_MAX` INT NULL,
  `FoldX` DECIMAL(10,10) NULL,
  `VARIANT_ID` INT NOT NULL,
  PRIMARY KEY (`STRUCTURAL_EFFECT_ID`),
  INDEX `fk_StructuralEffect_Variant1_idx` (`VARIANT_ID` ASC),
  UNIQUE INDEX `VARIANT_ID_UNIQUE` (`VARIANT_ID` ASC),
  CONSTRAINT `fk_StructuralEffect_Variant1`
    FOREIGN KEY (`VARIANT_ID`)
    REFERENCES `EdgoDB`.`Variant` (`VARIANT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`Disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`Disease` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`Disease` (
  `DISEASE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DISEASE_NAME` VARCHAR(45) NOT NULL,
  `INHERITANCE_PATTERN` VARCHAR(45) NULL,
  `VARIANT_ID` INT NOT NULL,
  PRIMARY KEY (`DISEASE_ID`),
  UNIQUE INDEX `DISEASE_NAME_UNIQUE` (`DISEASE_NAME` ASC),
  INDEX `fk_Disease_Variant1_idx` (`VARIANT_ID` ASC),
  CONSTRAINT `fk_Disease_Variant1`
    FOREIGN KEY (`VARIANT_ID`)
    REFERENCES `EdgoDB`.`Variant` (`VARIANT_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EdgoDB`.`OpenReadingFrame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EdgoDB`.`OpenReadingFrame` ;

CREATE TABLE IF NOT EXISTS `EdgoDB`.`OpenReadingFrame` (
  `CCSB_ORF_ID` INT NOT NULL,
  `ORF_LENGTH` INT NOT NULL,
  `REF_ORF_SEQ` VARCHAR(5000) NOT NULL,
  `ENTREZ_GENE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CCSB_ORF_ID`),
  INDEX `fk_OpenReadingFrame_Gene1_idx` (`ENTREZ_GENE_ID` ASC),
  CONSTRAINT `fk_OpenReadingFrame_Gene1`
    FOREIGN KEY (`ENTREZ_GENE_ID`)
    REFERENCES `EdgoDB`.`Gene` (`ENTREZ_GENE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
